Controllers/GebruikerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Testing0._1.Data;
using Testing0._1.Models;
using Microsoft.AspNetCore.Authorization;

namespace Testing0._1.Controllers
{
    [Authorize]
    public class GebruikerController : Controller
    {
        private readonly ApplicationDbContext _context;

        public GebruikerController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Gebruiker
        public async Task<IActionResult> Index()
        {
            return View(await _context.Gebruikers.Include(r => r.GebruikerTeams).ToListAsync());
        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Indexadmin()
        {
            return View(await _context.Gebruikers.Include(r => r.GebruikerTeams).ToListAsync());
        }

        public async Task<IActionResult> Details(int? id)
        {
            var applicationDbContext = _context.Uitslagen.Include(r => r.Rit).Include(r => r.Gebruiker).Where(r => r.GebruikerID == id).OrderBy(r => r.Rit.Datum);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Gebruiker/Details/5


        // GET: Gebruiker/Create
        [Authorize(Roles = "Admin")]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Gebruiker/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Authorize(Roles = "Admin")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("GebruikerID,Naam,Voornaam,Nationaliteit,Profielfoto,Score")] Gebruiker gebruiker)
        {
            if (ModelState.IsValid)
            {
                _context.Add(gebruiker);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(gebruiker);
        }

        // GET: Gebruiker/Edit/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var gebruiker = await _context.Gebruikers.FindAsync(id);
            if (gebruiker == null)
            {
                return NotFound();
            }
            return View(gebruiker);
        }

        // POST: Gebruiker/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Authorize(Roles = "Admin")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("GebruikerID,Naam,Voornaam,Nationaliteit,Profielfoto,Score")] Gebruiker gebruiker)
        {
            if (id != gebruiker.GebruikerID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(gebruiker);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!GebruikerExists(gebruiker.GebruikerID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(gebruiker);
        }

        // GET: Gebruiker/Delete/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var gebruiker = await _context.Gebruikers
                .FirstOrDefaultAsync(m => m.GebruikerID == id);
            if (gebruiker == null)
            {
                return NotFound();
            }

            return View(gebruiker);
        }

        // POST: Gebruiker/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var gebruiker = await _context.Gebruikers.FindAsync(id);
            _context.Gebruikers.Remove(gebruiker);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool GebruikerExists(int id)
        {
            return _context.Gebruikers.Any(e => e.GebruikerID == id);
        }

        public async Task<IActionResult> Ranking()
        {
            return View(await _context.Gebruikers.ToListAsync());
        }
    }
}

Controllers/RitController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Testing0._1.Data;
using Testing0._1.Models;
using Microsoft.AspNetCore.Authorization;

namespace Testing0._1.Controllers
{
    [Authorize]
    public class RitController : Controller
    {
        private readonly ApplicationDbContext _context;

        public RitController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Rit
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Ritten.Include(r => r.Race).Include(r => r.Ritsoort);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Rit/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var applicationDbContext = _context.Uitslagen.Include(r => r.Rit).Include(r => r.Gebruiker).Where(r => r.RitID == id).OrderBy(r => r.Resultaat);

            if (applicationDbContext == null)
            {
                return NotFound();
            }

            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Rit/Create
        [Authorize(Roles = "Admin")]
        public IActionResult Create()
        {
            ViewData["RaceID"] = new SelectList(_context.Races, "RaceID", "Naam");
            ViewData["RitsoortID"] = new SelectList(_context.Ritsoorten, "RitsoortID", "Naam");
            return View();
        }

        // POST: Rit/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Authorize(Roles = "Admin")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("RitID,Afstand,Naam,Datum,Profielfoto,RitsoortID,RaceID")] Rit rit)
        {
            if (ModelState.IsValid)
            {
                _context.Add(rit);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["RaceID"] = new SelectList(_context.Races, "RaceID", "RaceID", rit.RaceID);
            ViewData["RitsoortID"] = new SelectList(_context.Ritsoorten, "RitsoortID", "RitsoortID", rit.RitsoortID);
            return View(rit);
        }

        // GET: Rit/Edit/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var rit = await _context.Ritten.FindAsync(id);
            if (rit == null)
            {
                return NotFound();
            }
            ViewData["RaceID"] = new SelectList(_context.Races, "RaceID", "RaceID", rit.RaceID);
            ViewData["RitsoortID"] = new SelectList(_context.Ritsoorten, "RitsoortID", "RitsoortID", rit.RitsoortID);
            return View(rit);
        }

        // POST: Rit/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Authorize(Roles = "Admin")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("RitID,Afstand,Naam,Datum,Profielfoto,RitsoortID,RaceID")] Rit rit)
        {
            if (id != rit.RitID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(rit);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!RitExists(rit.RitID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["RaceID"] = new SelectList(_context.Races, "RaceID", "RaceID", rit.RaceID);
            ViewData["RitsoortID"] = new SelectList(_context.Ritsoorten, "RitsoortID", "RitsoortID", rit.RitsoortID);
            return View(rit);
        }

        // GET: Rit/Delete/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var rit = await _context.Ritten
                .Include(r => r.Race)
                .Include(r => r.Ritsoort)
                .FirstOrDefaultAsync(m => m.RitID == id);
            if (rit == null)
            {
                return NotFound();
            }

            return View(rit);
        }

        // POST: Rit/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var rit = await _context.Ritten.FindAsync(id);
            _context.Ritten.Remove(rit);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool RitExists(int id)
        {
            return _context.Ritten.Any(e => e.RitID == id);
        }
    }
}

Controllers/UitslagController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Testing0._1.Data;
using Testing0._1.Models;
using Microsoft.AspNetCore.Authorization;

namespace Testing0._1.Controllers
{
    [Authorize] 
    public class UitslagController : Controller
    {
        private readonly ApplicationDbContext _context;

        public UitslagController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Uitslag
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Index(string searchname)
        {

            if (!String.IsNullOrEmpty(searchname))
            {
                var applicationDbContext = _context.Uitslagen.Include(u => u.Gebruiker).Include(u => u.Rit).Where(u => u.Gebruiker.Naam.Contains(searchname)|| u.Gebruiker.Voornaam.Contains(searchname));
                return View(await applicationDbContext.ToListAsync());
            }
            else
            {
                var applicationDbContext = _context.Uitslagen.Include(u => u.Gebruiker).Include(u => u.Rit);
                return View(await applicationDbContext.ToListAsync());
            }
        }

        // GET: Uitslag/Details/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var uitslag = await _context.Uitslagen
                .Include(u => u.Gebruiker)
                .Include(u => u.Rit)
                .Include(u => u.Rit.Ritsoort)
                .FirstOrDefaultAsync(m => m.UitslagID == id);
            if (uitslag == null)
            {
                return NotFound();
            }

            return View(uitslag);
        }

        // GET: Uitslag/Create
        [Authorize(Roles = "Admin")]
        public IActionResult Create()
        {
            ViewData["GebruikerID"] = new SelectList(_context.Gebruikers, "GebruikerID", "VolledigeNaam");
            ViewData["RitID"] = new SelectList(_context.Ritten, "RitID", "Naam");
            return View();
        }

        // POST: Uitslag/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Authorize(Roles = "Admin")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("UitslagID,Puntenklassement,Bergklassement,Strijdlustklassement,Resultaat,Algemeenklassement,RitID,GebruikerID")] Uitslag uitslag)
        {
            if (ModelState.IsValid)
            {
                _context.Add(uitslag);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["GebruikerID"] = new SelectList(_context.Gebruikers, "GebruikerID", "VolledigeNaam", uitslag.GebruikerID);
            ViewData["RitID"] = new SelectList(_context.Ritten, "RitID", "Naam", uitslag.RitID);
            return View(uitslag);
        }

        // GET: Uitslag/Edit/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var uitslag = await _context.Uitslagen.FindAsync(id);
            if (uitslag == null)
            {
                return NotFound();
            }
            ViewData["GebruikerID"] = new SelectList(_context.Gebruikers, "GebruikerID", "VolledigeNaam", uitslag.GebruikerID);
            ViewData["RitID"] = new SelectList(_context.Ritten, "RitID", "Naam", uitslag.RitID);
            return View(uitslag);
        }

        // POST: Uitslag/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Authorize(Roles = "Admin")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("UitslagID,Puntenklassement,Bergklassement,Strijdlustklassement,Resultaat,Algemeenklassement,RitID,GebruikerID")] Uitslag uitslag)
        {
            if (id != uitslag.UitslagID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(uitslag);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!UitslagExists(uitslag.UitslagID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["GebruikerID"] = new SelectList(_context.Gebruikers, "GebruikerID", "VolledigeNaam", uitslag.GebruikerID);
            ViewData["RitID"] = new SelectList(_context.Ritten, "RitID", "Naam", uitslag.RitID);
            return View(uitslag);
        }

        // GET: Uitslag/Delete/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var uitslag = await _context.Uitslagen
                .Include(u => u.Gebruiker)
                .Include(u => u.Rit)
                .FirstOrDefaultAsync(m => m.UitslagID == id);
            if (uitslag == null)
            {
                return NotFound();
            }

            return View(uitslag);
        }

        // POST: Uitslag/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var uitslag = await _context.Uitslagen.FindAsync(id);
            _context.Uitslagen.Remove(uitslag);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool UitslagExists(int id)
        {
            return _context.Uitslagen.Any(e => e.UitslagID == id);
        }
    }
}

Views/Uitslag/Create.cshtml
@model Testing0._1.Models.Uitslag

@{
    ViewData["Title"] = "Create";
}
<h1>Placeholder</h1>
<p>Placeholder</p>

<h1>Create</h1>

<h4>Uitslag</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Resultaat" class="control-label"></label>
                <input asp-for="Resultaat" class="form-control" />
                <span asp-validation-for="Resultaat" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label>Tijd</label>
                <input asp-for="Algemeenklassement" class="form-control" />
                <span asp-validation-for="Algemeenklassement" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label>Rit</label>
                <select asp-for="RitID" class="form-control" asp-items="ViewBag.RitID"></select>
            </div>
            <div class="form-group">
                <label>Renner</label>
                <select asp-for="GebruikerID" class="form-control" asp-items="ViewBag.GebruikerID"></select>
            </div>
            <p>
                <button class="btn btn-primary" type="button" data-toggle="collapse" data-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">
                    Klassementen
                </button>
            </p>
            <div class="collapse" id="collapseExample">
                <div class="form-group">
                    <label asp-for="Puntenklassement" class="control-label"></label>
                    <input asp-for="Puntenklassement" class="form-control" />
                    <span asp-validation-for="Puntenklassement" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Bergklassement" class="control-label"></label>
                    <input asp-for="Bergklassement" class="form-control" />
                    <span asp-validation-for="Bergklassement" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Strijdlustklassement" class="control-label"></label>
                    <input asp-for="Strijdlustklassement" class="form-control" />
                    <span asp-validation-for="Strijdlustklassement" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Uitslag/Delete.cshtml
@model Testing0._1.Models.Uitslag

@{
    ViewData["Title"] = "Delete";
}
<h1>Placeholder</h1>
<p>Placeholder</p>

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Uitslag</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Puntenklassement)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Puntenklassement)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Bergklassement)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Bergklassement)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Strijdlustklassement)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Strijdlustklassement)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Resultaat)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Resultaat)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Algemeenklassement)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Algemeenklassement)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Rit)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Rit.RitID)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Gebruiker)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Gebruiker.Naam)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="UitslagID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Uitslag/Details.cshtml
@model Testing0._1.Models.Uitslag

@{
    ViewData["Title"] = "Details";
}
<h1>Placeholder</h1>
<p>Placeholder</p>

<h1>Details</h1>

<div>
    <h4>Uitslag</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            Renner
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Gebruiker.VolledigeNaam)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Resultaat)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Resultaat)
        </dd>
        <dt class="col-sm-2">
            Tijd
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Algemeenklassement)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Rit)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Rit.Naam)
        </dd>
        <dt class="col-sm-2">
            Punten
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Puntenklassement)
        </dd>
        <dt class="col-sm-2">
            Berg
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Bergklassement)
        </dd>
        <dt class="col-sm-2">
            Strijdlust
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Strijdlustklassement)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.UitslagID">Edit</a> |
    <a asp-action="Index">Back to Uitslagen</a>
</div>

Views/Uitslag/Edit.cshtml
@model Testing0._1.Models.Uitslag

@{
    ViewData["Title"] = "Edit";
}
<h1>Placeholder</h1>
<p>Placeholder</p>

<h1>Edit</h1>

<h4>Uitslag</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="UitslagID" />
            <div class="form-group">
                <label asp-for="Resultaat" class="control-label"></label>
                <input asp-for="Resultaat" class="form-control" />
                <span asp-validation-for="Resultaat" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label>Tijd</label>
                <input asp-for="Algemeenklassement" class="form-control" />
                <span asp-validation-for="Algemeenklassement" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label>Rit</label>
                <select asp-for="GebruikerID" class="form-control" asp-items="ViewBag.GebruikerID"></select>
                <span asp-validation-for="GebruikerID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label>Renner</label>
                <select asp-for="RitID" class="form-control" asp-items="ViewBag.RitID"></select>
                <span asp-validation-for="RitID" class="text-danger"></span>
            </div>
            <p>
                <button class="btn btn-primary" type="button" data-toggle="collapse" data-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">
                    Klassementen
                </button>
            </p>
            <div class="collapse" id="collapseExample">
                <div class="form-group">
                    <label asp-for="Puntenklassement" class="control-label"></label>
                    <input asp-for="Puntenklassement" class="form-control" />
                    <span asp-validation-for="Puntenklassement" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Bergklassement" class="control-label"></label>
                    <input asp-for="Bergklassement" class="form-control" />
                    <span asp-validation-for="Bergklassement" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Strijdlustklassement" class="control-label"></label>
                    <input asp-for="Strijdlustklassement" class="form-control" />
                    <span asp-validation-for="Strijdlustklassement" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Uitslag/Index.cshtml
@model IEnumerable<Testing0._1.Models.Uitslag>

@{
    ViewData["Title"] = "Index";
}
<h1>Placeholder</h1>
<p>Placeholder</p>

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
@using (Html.BeginForm())
{

    <p>
        Name  : @Html.TextBox("searchname")
        <input name="kut" type="submit" value="Search" />
    </p>


}
<table class="table" id="listtable">
    <thead>
        <tr>
            <th>
                Renner
            </th>
            <th>
                Resultaat
            </th>
            <th>
                Race
            </th>
            <th>
                Tijd
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    <a asp-controller="Gebruiker" asp-action="Details" asp-route-id="@item.GebruikerID">@Html.DisplayFor(modelItem => item.Gebruiker.VolledigeNaam)</a>

                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Resultaat)
                </td>
                <td>
                    <a asp-controller="Rit" asp-action="Details" asp-route-id="@item.RitID">@Html.DisplayFor(modelItem => item.Rit.Naam)</a>
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Algemeenklassement)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.UitslagID">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.UitslagID">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.UitslagID">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>