Models/Rit.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Testing0._1.Models
{
    public class Rit
    {
        public int RitID { get; set; }
        public int Afstand { get; set; }
        public string Naam { get; set; }
        public DateTime Datum { get; set; }
        public string Profielfoto { get; set; }
        public int RitsoortID { get; set; }
        public Ritsoort Ritsoort { get; set; }
        public int RaceID { get; set; }
        public Race Race { get; set; }
    }
}

Controllers/GebruikerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Testing0._1.Data;
using Testing0._1.Models;
using Microsoft.AspNetCore.Authorization;

namespace Testing0._1.Controllers
{
    [Authorize]
    public class GebruikerController : Controller
    {
        private readonly ApplicationDbContext _context;

        public GebruikerController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Gebruiker
        public async Task<IActionResult> Index()
        {
            return View(await _context.Gebruikers.Include(r => r.GebruikerTeams).ToListAsync());
        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Indexadmin()
        {
            return View(await _context.Gebruikers.Include(r => r.GebruikerTeams).ToListAsync());
        }

        public async Task<IActionResult> Details(int? id)
        {
            var applicationDbContext = _context.Uitslagen.Include(r => r.Rit).Include(r => r.Gebruiker).Where(r => r.GebruikerID == id).OrderBy(r => r.Rit.Datum);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Gebruiker/Details/5


        // GET: Gebruiker/Create
        [Authorize(Roles = "Admin")]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Gebruiker/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Authorize(Roles = "Admin")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("GebruikerID,Naam,Voornaam,Nationaliteit,Profielfoto,Score")] Gebruiker gebruiker)
        {
            if (ModelState.IsValid)
            {
                _context.Add(gebruiker);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(gebruiker);
        }

        // GET: Gebruiker/Edit/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var gebruiker = await _context.Gebruikers.FindAsync(id);
            if (gebruiker == null)
            {
                return NotFound();
            }
            return View(gebruiker);
        }

        // POST: Gebruiker/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Authorize(Roles = "Admin")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("GebruikerID,Naam,Voornaam,Nationaliteit,Profielfoto,Score")] Gebruiker gebruiker)
        {
            if (id != gebruiker.GebruikerID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(gebruiker);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!GebruikerExists(gebruiker.GebruikerID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(gebruiker);
        }

        // GET: Gebruiker/Delete/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var gebruiker = await _context.Gebruikers
                .FirstOrDefaultAsync(m => m.GebruikerID == id);
            if (gebruiker == null)
            {
                return NotFound();
            }

            return View(gebruiker);
        }

        // POST: Gebruiker/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var gebruiker = await _context.Gebruikers.FindAsync(id);
            _context.Gebruikers.Remove(gebruiker);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool GebruikerExists(int id)
        {
            return _context.Gebruikers.Any(e => e.GebruikerID == id);
        }

        public async Task<IActionResult> Ranking()
        {
            return View(await _context.Gebruikers.ToListAsync());
        }
    }
}

Controllers/RaceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Testing0._1.Data;
using Testing0._1.Models;
using Microsoft.AspNetCore.Authorization;

namespace Testing0._1.Controllers
{
    [Authorize]
    public class RaceController : Controller
    {
        private readonly ApplicationDbContext _context;

        public RaceController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Race
        public async Task<IActionResult> Index()
        {
            return View(await _context.Races.ToListAsync()); 
        }

        public async Task<IActionResult> Klassement(int? id)
        {
            var applicationDbContext = _context.Uitslagen.Include(r => r.Gebruiker).Include(r => r.Rit).ThenInclude(r => r.Race).Where(r => r.Rit.RaceID == id);
            return View(await applicationDbContext.ToListAsync());
        }
        public async Task<IActionResult> Details(int? id)
        {
            var applicationDbContext = _context.Uitslagen.Include(r => r.Gebruiker).Include(r => r.Rit).ThenInclude(r => r.Race).Where(r => r.Rit.RaceID == id);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Race/Create
        [Authorize(Roles = "Admin")]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Race/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Authorize(Roles = "Admin")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("RaceID,Naam,Finished,Startdatum,Aantalritten")] Race race)
        {
            if (ModelState.IsValid)
            {
                _context.Add(race);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(race);
        }

        // GET: Race/Edit/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var race = await _context.Races.FindAsync(id);
            if (race == null)
            {
                return NotFound();
            }
            return View(race);
        }

        // POST: Race/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Authorize(Roles = "Admin")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("RaceID,Naam,Finished,Startdatum,Aantalritten")] Race race)
        {
            if (id != race.RaceID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(race);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!RaceExists(race.RaceID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(race);
        }

        // GET: Race/Delete/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var race = await _context.Races
                .FirstOrDefaultAsync(m => m.RaceID == id);
            if (race == null)
            {
                return NotFound();
            }

            return View(race);
        }

        // POST: Race/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var race = await _context.Races.FindAsync(id);
            _context.Races.Remove(race);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool RaceExists(int id)
        {
            return _context.Races.Any(e => e.RaceID == id);
        }
    }
}

Controllers/UitslagController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Testing0._1.Data;
using Testing0._1.Models;
using Microsoft.AspNetCore.Authorization;

namespace Testing0._1.Controllers
{
    [Authorize] 
    public class UitslagController : Controller
    {
        private readonly ApplicationDbContext _context;

        public UitslagController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Uitslag
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Index(string searchname)
        {

            if (!String.IsNullOrEmpty(searchname))
            {
                var applicationDbContext = _context.Uitslagen.Include(u => u.Gebruiker).Include(u => u.Rit).Where(u => u.Gebruiker.Naam.Contains(searchname)|| u.Gebruiker.Voornaam.Contains(searchname));
                return View(await applicationDbContext.ToListAsync());
            }
            else
            {
                var applicationDbContext = _context.Uitslagen.Include(u => u.Gebruiker).Include(u => u.Rit);
                return View(await applicationDbContext.ToListAsync());
            }
        }

        // GET: Uitslag/Details/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var uitslag = await _context.Uitslagen
                .Include(u => u.Gebruiker)
                .Include(u => u.Rit)
                .Include(u => u.Rit.Ritsoort)
                .FirstOrDefaultAsync(m => m.UitslagID == id);
            if (uitslag == null)
            {
                return NotFound();
            }

            return View(uitslag);
        }

        // GET: Uitslag/Create
        [Authorize(Roles = "Admin")]
        public IActionResult Create()
        {
            ViewData["GebruikerID"] = new SelectList(_context.Gebruikers, "GebruikerID", "VolledigeNaam");
            ViewData["RitID"] = new SelectList(_context.Ritten, "RitID", "Naam");
            return View();
        }

        // POST: Uitslag/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Authorize(Roles = "Admin")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("UitslagID,Puntenklassement,Bergklassement,Strijdlustklassement,Resultaat,Algemeenklassement,RitID,GebruikerID")] Uitslag uitslag)
        {
            if (ModelState.IsValid)
            {
                _context.Add(uitslag);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["GebruikerID"] = new SelectList(_context.Gebruikers, "GebruikerID", "VolledigeNaam", uitslag.GebruikerID);
            ViewData["RitID"] = new SelectList(_context.Ritten, "RitID", "Naam", uitslag.RitID);
            return View(uitslag);
        }

        // GET: Uitslag/Edit/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var uitslag = await _context.Uitslagen.FindAsync(id);
            if (uitslag == null)
            {
                return NotFound();
            }
            ViewData["GebruikerID"] = new SelectList(_context.Gebruikers, "GebruikerID", "VolledigeNaam", uitslag.GebruikerID);
            ViewData["RitID"] = new SelectList(_context.Ritten, "RitID", "Naam", uitslag.RitID);
            return View(uitslag);
        }

        // POST: Uitslag/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Authorize(Roles = "Admin")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("UitslagID,Puntenklassement,Bergklassement,Strijdlustklassement,Resultaat,Algemeenklassement,RitID,GebruikerID")] Uitslag uitslag)
        {
            if (id != uitslag.UitslagID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(uitslag);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!UitslagExists(uitslag.UitslagID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["GebruikerID"] = new SelectList(_context.Gebruikers, "GebruikerID", "VolledigeNaam", uitslag.GebruikerID);
            ViewData["RitID"] = new SelectList(_context.Ritten, "RitID", "Naam", uitslag.RitID);
            return View(uitslag);
        }

        // GET: Uitslag/Delete/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var uitslag = await _context.Uitslagen
                .Include(u => u.Gebruiker)
                .Include(u => u.Rit)
                .FirstOrDefaultAsync(m => m.UitslagID == id);
            if (uitslag == null)
            {
                return NotFound();
            }

            return View(uitslag);
        }

        // POST: Uitslag/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var uitslag = await _context.Uitslagen.FindAsync(id);
            _context.Uitslagen.Remove(uitslag);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool UitslagExists(int id)
        {
            return _context.Uitslagen.Any(e => e.UitslagID == id);
        }
    }
}

Views/Rit/Create.cshtml
@model Testing0._1.Models.Rit

@{
    ViewData["Title"] = "Create";
}
<h1>Placeholder</h1>
<p>Placeholder</p>

<h1>Create</h1>

<h4>Rit</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Afstand" class="control-label"></label>
                <input asp-for="Afstand" class="form-control" />
                <span asp-validation-for="Afstand" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Naam" class="control-label"></label>
                <input asp-for="Naam" class="form-control" />
                <span asp-validation-for="Naam" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Datum" class="control-label"></label>
                <input asp-for="Datum" class="form-control" />
                <span asp-validation-for="Datum" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Profielfoto" class="control-label"></label>
                <input asp-for="Profielfoto" class="form-control" />
                <span asp-validation-for="Profielfoto" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RitsoortID" class="control-label"></label>
                <select asp-for="RitsoortID" class="form-control" asp-items="ViewBag.RitsoortID"></select>
            </div>
            <div class="form-group">
                <label asp-for="RaceID" class="control-label"></label>
                <select asp-for="RaceID" class="form-control" asp-items="ViewBag.RaceID"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Rit/Delete.cshtml
@model Testing0._1.Models.Rit

@{
    ViewData["Title"] = "Delete";
}
<h1>Placeholder</h1>
<p>Placeholder</p>

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Rit</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Afstand)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Afstand)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Naam)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Naam)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Datum)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Datum)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Profielfoto)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Profielfoto)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Ritsoort)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Ritsoort.RitsoortID)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Race)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Race.RaceID)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="RitID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Rit/Details.cshtml
@model IEnumerable<Testing0._1.Models.Uitslag>

@{
    ViewData["Title"] = "Index";
    int x = 0;
    int raceid = 0;
    foreach (var item in Model)
    {
        while (x == 0)
        {
            <h1>@Html.DisplayFor(modelItem => item.Rit.Naam)</h1>
            raceid = item.Rit.RaceID;
            x += 1;

            @if (this.User.IsInRole("Admin"))
            {
                <h1>Placeholder</h1>
                <p>Placeholder</p>
                <p>
                    <img src="@Html.DisplayFor(modelItem => item.Rit.Profielfoto)" />
                    <a asp-controller="Uitslag" asp-action="Create">Niewe uitslag toevoegen</a>
                </p>
            }

        }
    }
}




<table class="table" id="listtable">
    <thead>
        <tr>
            <th>
                Plaats
            </th>
            <th>
                Naam
            </th>
            <th>
                Tijd
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Resultaat)
                </td>
                <td>
                    <a asp-controller="Gebruiker" asp-action="Details" asp-route-id="@item.GebruikerID">@Html.DisplayFor(modelItem => item.Gebruiker.VolledigeNaam)</a>
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Algemeenklassement)
                </td>
                <td>
                    @if (this.User.IsInRole("Admin"))
                    {
                        <a asp-action="Edit" asp-route-id="@item.RitID">Edit</a>
                    }
                    @if (this.User.IsInRole("Admin"))
                    {
                        <a asp-action="Details" asp-route-id="@item.RitID">Details</a>
                    }
                    @if (this.User.IsInRole("Admin"))
                    {
                        <a asp-action="Delete" asp-route-id="@item.RitID">Delete</a>
                    }
                </td>
            </tr>
        }
    </tbody>
</table>

<div>
    <a asp-controller="Race" asp-action="Details" asp-route-id="@raceid">Naar alle ritten</a>
</div>

Views/Rit/Edit.cshtml
@model Testing0._1.Models.Rit

@{
    ViewData["Title"] = "Edit";
}
<h1>Placeholder</h1>
<p>Placeholder</p>

<h1>Edit</h1>

<h4>Rit</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="RitID" />
            <div class="form-group">
                <label asp-for="Afstand" class="control-label"></label>
                <input asp-for="Afstand" class="form-control" />
                <span asp-validation-for="Afstand" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Naam" class="control-label"></label>
                <input asp-for="Naam" class="form-control" />
                <span asp-validation-for="Naam" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Datum" class="control-label"></label>
                <input asp-for="Datum" class="form-control" />
                <span asp-validation-for="Datum" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Profielfoto" class="control-label"></label>
                <input asp-for="Profielfoto" class="form-control" />
                <span asp-validation-for="Profielfoto" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RitsoortID" class="control-label"></label>
                <select asp-for="RitsoortID" class="form-control" asp-items="ViewBag.RitsoortID"></select>
                <span asp-validation-for="RitsoortID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RaceID" class="control-label"></label>
                <select asp-for="RaceID" class="form-control" asp-items="ViewBag.RaceID"></select>
                <span asp-validation-for="RaceID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Rit/Index.cshtml
@model IEnumerable<Testing0._1.Models.Rit>

@{
    ViewData["Title"] = "Index";
}
<h1>Placeholder</h1>
<p>Placeholder</p>

<h1>Alle Ritten</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table" id="listtable">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Afstand)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Naam)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Datum)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Ritsoort)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Race)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Afstand)  km
                </td>
                <td>
                    <a asp-action="Details" asp-route-id="@item.RitID">@Html.DisplayFor(modelItem => item.Naam)</a>
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Datum)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Ritsoort.Naam)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Race.Naam)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.RitID">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.RitID">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.RitID">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>